# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/markdown-voc/',
                'doc_host': 'https://charlesvardeman.github.io',
                'git_url': 'https://github.com/charlesvardeman/markdown-voc/',
                'lib_path': 'markdown_voc'},
  'syms': { 'markdown_voc.core': { 'markdown_voc.core.extract_prefixes': ('core.html#extract_prefixes', 'markdown_voc/core.py'),
                                   'markdown_voc.core.extract_triples': ('core.html#extract_triples', 'markdown_voc/core.py'),
                                   'markdown_voc.core.main': ('core.html#main', 'markdown_voc/core.py'),
                                   'markdown_voc.core.markdown_ld_convert': ('core.html#markdown_ld_convert', 'markdown_voc/core.py'),
                                   'markdown_voc.core.markdown_ld_to_jsonld': ('core.html#markdown_ld_to_jsonld', 'markdown_voc/core.py'),
                                   'markdown_voc.core.markdown_ld_to_triples': ('core.html#markdown_ld_to_triples', 'markdown_voc/core.py'),
                                   'markdown_voc.core.markdown_ld_to_turtle': ('core.html#markdown_ld_to_turtle', 'markdown_voc/core.py'),
                                   'markdown_voc.core.triples_to_rdflib_graph': ( 'core.html#triples_to_rdflib_graph',
                                                                                  'markdown_voc/core.py'),
                                   'markdown_voc.core.triples_to_turtle': ('core.html#triples_to_turtle', 'markdown_voc/core.py')}}}
